In [41]:
import numpy as np
from IPython.display import clear_output
import time

In [23]:
from numpy.random import randint, choice

In [5]:
import gym

In [6]:
env = gym.make('FrozenLake-v0')

In [46]:
def random_step(prev_state, policy):
    return choice([0, 1, 2, 3], p=policy[prev_state])

In [47]:
n_actions = env.action_space.n
n_states = env.observation_space.n

In [55]:
def make_onehot(class_, num_classes):
    b = np.zeros((num_classes), dtype=np.int)
    b[class_] = 1
    return b

In [60]:
make_onehot(3,4)

array([0, 0, 0, 1])

In [73]:
def softmax(array):
    return np.exp(array) / np.sum(np.exp(array))

In [205]:
def laplas(array):
    smooth_const = 1.
    return (array + smooth_const) / np.sum(array + smooth_const)

In [206]:
softmax(make_onehot(2,4))

array([ 0.1748777 ,  0.1748777 ,  0.47536689,  0.1748777 ])

In [207]:
laplas(make_onehot(2,4))

array([ 0.2,  0.2,  0.4,  0.2])

In [373]:
policy = np.zeros((16 , 4)) + 0.25

In [406]:
elite_sessions = []
elite_rewards = []
for _ in range(2000):
    session = np.zeros((16, 4), dtype=np.int)
    obs = env.reset()
    #env.render()
    done = False
    steps = 0
    while not done:
        steps += 1
        direction = random_step(obs, policy)
        session[obs] = make_onehot(direction, 4)
        obs, reward, done, info = env.step(direction)
        
        if obs + 1 == n_states:
            elite_sessions.append(session)
            elite_rewards.append(-steps)
        #clear_output()
        #env.render()                               
        #time.sleep(1)
print('Агентов выжило: ', len(elite_sessions))

Агентов выжило:  204


In [407]:
res = (np.array(elite_sessions)[np.argsort(elite_rewards)])[:int(len(elite_sessions)*0.4)]
#res = np.array(elite_sessions)
res = np.sum(res, axis=0)
print(res)
res = np.apply_along_axis(softmax, 1, res)
print(res)
policy = res

[[81  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [81  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0 81  0  0]
 [ 0  0 81  0]
 [ 0 52  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0 72  0]
 [ 0  0  0 81]
 [ 0  0  0  0]]
[[  1.00000000e+00   6.63967720e-36   6.63967720e-36   6.63967720e-36]
 [  2.50000000e-01   2.50000000e-01   2.50000000e-01   2.50000000e-01]
 [  2.50000000e-01   2.50000000e-01   2.50000000e-01   2.50000000e-01]
 [  2.50000000e-01   2.50000000e-01   2.50000000e-01   2.50000000e-01]
 [  1.00000000e+00   6.63967720e-36   6.63967720e-36   6.63967720e-36]
 [  2.50000000e-01   2.50000000e-01   2.50000000e-01   2.50000000e-01]
 [  2.50000000e-01   2.50000000e-01   2.50000000e-01   2.50000000e-01]
 [  2.50000000e-01   2.50000000e-01   2.50000000e-01   2.50000000e-01]
 [  6.63967720e-36   1.00000000e+00   6.63967720e-36   6.63967720e-36]
 [  6.63967720e-36   6.63967720e-36   1.00000000e+00   6.63967720e-36]
 [  2.61027907e-23   1.00000000e+00   2.61027907e

In [241]:
#env.reset()
#env.step(2)

(1, 0.0, False, {'prob': 0.3333333333333333})